improvement set os

diff --git a/tasks/set-os.yaml b/tasks/set-os.yaml
--- a/tasks/set-os.yaml
+++ b/tasks/set-os.yaml
@@ -7,29 +7,33 @@ spec:
   desc: set a better kernel parameters for kubernetes host
   steps:
     - name: install packages
-      content: apt-get install -y openssl socat conntrack ipset ebtables chrony ipvsadm || echo "install failed"
+      content: |
+        apt-get install -y openssl socat conntrack ipset ebtables chrony ipvsadm || echo "install failed"
     - name: Max PID
-      content: echo "kernel.pid_max=4194303 " >> /etc/sysctl.conf
+      content: |
+        echo "kernel.pid_max=4194303 " >> /etc/sysctl.conf
     - name: Max Thread
-      content: echo "kernel.threads-max=4194303 " >> /etc/sysctl.conf
+      content: |
+        echo "kernel.threads-max=4194303 " >> /etc/sysctl.conf
     - name: Max Conntrack
-      content:
+      content: |
         echo "net.netfilter.nf_conntrack_max=3200000" >> /etc/sysctl.conf
         echo "net.netfilter.nf_conntrack_tcp_be_liberal=1" >> /etc/sysctl.conf
         echo "net.netfilter.nf_conntrack_tcp_loose=1" >> /etc/sysctl.conf
         echo "net.netfilter.nf_conntrack_buckets=1600512" >> /etc/sysctl.conf
         echo "net.netfilter.nf_conntrack_tcp_timeout_time_wait=30" >> /etc/sysctl.conf
     - name: Max ARP Router
-      content:
+      content: |
         echo "net.ipv4.neigh.default.gc_thresh1=80000" >> /etc/sysctl.conf
         echo "net.ipv4.neigh.default.gc_thresh2=90000" >> /etc/sysctl.conf
         echo "net.ipv4.neigh.default.gc_thresh3=100000" >> /etc/sysctl.conf
     - name: ipv4
-      content:
+      content: |
         echo "net.ipv4.tcp_max_orphans=32768" >> /etc/sysctl.conf
         echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
     - name: fd
-      content: echo "fs.file-max=1048576" >> /etc/sysctl.conf
+      content: |
+        echo "fs.file-max=1048576" >> /etc/sysctl.conf
         echo "fs.inotify.max_user_instances=8192" >> /etc/sysctl.conf
         echo "fs.inotify.max_user_watches=524288" >> /etc/sysctl.conf
     - name: set pipe-user-pages-soft
@@ -38,13 +42,13 @@ spec:
     - name: apply change
       content: sysctl -p
     - name: max user processes
-      content: |+
+      content: |
         sed -i "/soft nproc/d" /etc/security/limits.conf ;
         echo "* soft nproc  262144" >> /etc/security/limits.conf  
         sed -i "/* hard nproc/d" /etc/security/limits.conf ;
         echo "* hard nproc  262144" >> /etc/security/limits.conf
     - name: max user processes
-      content: |+
+      content: |
         sed -i "/soft nofile/d" /etc/security/limits.conf ;
         echo "* soft nofile  1048576" >> /etc/security/limits.conf  
         sed -i "/* hard nofile/d" /etc/security/limits.conf ;
